[package]
name = "code"
version = "0.1.0"
authors = ["martin <martin.papanek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "module_addition"
path = "src/bin/module_addition.rs"